### ISSUE TITLE
container 101 tutorial - make cluster approach does not work

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/contiv.github.io#144]
make cluster and then running installer using cfg.yaml does not work. Procedure mentioned there does not specify about cfg.yaml.

Need to remove that stuff.

**Comment by rhim** [comment]
disagree with "make cluster and then running installer using cfg.yaml does not work. Procedure mentioned there does not specify about cfg.yaml."

It is .cfg.yaml. Did it not work because of typo?

I think having these steps are good to describe a workflow that ppl will do in real life. So I strongly recommend leaving these here.

**Comment by gaurav-dalvi** [comment]
No i tired with `cfg.yaml` as well. It did not work. We need to get that content out of this tutorial. Goal is to learn contiv and not contiv installer.
