### ISSUE TITLE
kubernetes example redirects to multicast examples

### ISSUE THREAD

**Issue by abhinandanpb** [contiv/contiv.github.io#93]

**Comment by stacykor** [comment]
Thanks for the heads-up. On the old site, these links pointed just to Nomad and Multicast rather than to actual docker and kubernetes examples. With Nomad removed, there was just mulitcast.

There are two demo videos for Docker and Kubernetes with ACI:

https://www.youtube.com/watch?v=AHH1ACCMrm0 
https://www.youtube.com/watch?v=Eebq8KNo_XU
